= Random Walk Example Model
Version 1.0 September 2021
:toc2:
:icons: font
:numbered:
:website: http://repast.github.io
:xrefstyle: full
:imagesdir: images
:source-highlighter: pygments

== Overview

The random walk model is simple model intended as introduction to coding a Repast4Py simulation.
The model consists of a number of agents moving at random around a two-dimensional grid and logging 
the aggregate and agent-level colocation counts. Each timestep the following occurs:

1. All the agents (_walkers_) choose a random direction and move one unit in that direction.
2. All the agents count the number of other agents they _meet_ at their current location by
determining the number of colocated agents at their grid locations.
3. The sum, minimum, and maxiumum number of agents met are calculated across all process ranks, and these 
values are logged as the total, minimum, and maximum `meet` values.

In addition, every 10 timesteps: 

1. The individual agent _meet_ counts are logged across all the process ranks.

TODO: Put the User Guide model_101.adoc text here
