version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: dsheeler/repast4py
        auth:
          username: dsheeler
          password: DH1mbm666  # context / project UI env-var reference
    steps:
      - checkout
      - run: CC=mpicc CXX=mpicxx python setup.py build_ext --inplace
  test:
    docker:
      - image:  dsheeler/repast4py
        auth:
          username: dsheeler
          password: DH1mbm666  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
