version: 2.1

# Define the jobs we want to run for this project
executors:
  build:
    docker:
      - image: dsheeler/repast4py
        auth:
          username: dsheeler
          password: DH1mbm666  # context / project UI env-var reference
jobs:
  test_single:
    executor: build
    steps:
      - checkout
      - run: CC=mpicc CXX=mpicxx python setup.py build_ext --inplace
      - run:
          python -m unittest discover tests
          #mpirun -n 9 python -m unittest tests.shared_obj_tests &&
  test_2d_shared_obj:
    executor: build
    steps:
      - checkout
      - run: CC=mpicc CXX=mpicxx python setup.py build_ext --inplace
      - run:
          mpirun -n 9 python -m unittest tests.shared_obj_tests
          #mpirun -n 18 python -m unittest tests.shared_obj_tests.SharedGridTests.test_buffer_data_3d &&
  test_2d_shared_vl:
    executor: build
    steps:
      - checkout
      - run: CC=mpicc CXX=mpicxx python setup.py build_ext --inplace
      - run:
          mpirun -n 9 python -m unittest tests.shared_vl_tests
   test_buffer_data_3d:
    executor: build
    steps:
      - checkout
      - run: CC=mpicc CXX=mpicxx python setup.py build_ext --inplace
      - run:
          mpirun -n 18 python -m unittest tests.shared_obj_tests.SharedGridTests.test_buffer_data_3d
          #mpirun -n 18 python -m unittest tests.shared_obj_tests.SharedGridTests.test_buffer_data_3d_periodic &&
          #mpirun -n 18 python -m unittest tests.shared_vl_tests.SharedValueLayerTests.test_buffers_3x3x3_periodic &&
          #mpirun -n 18 python -m unittest tests.shared_vl_tests.SharedValueLayerTests.test_buffers_3x3x3_sticky 
# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - test_single
      - test_2d_shared_obj
      - test_2d_shared_vl
      - test_buffer_data_3d
