== Cross-Process Code Requirements
We've seen in the <<_distributed_simulation, Distributed Simulation>> section how ghost agents
(non-local copies) are used 
to stitch a simulation together across processes and that when agents move out of their local
grid or continuous space subsection they are moved to the process responsible for the destination
subsection. While much of this is handled internally by Repast4Py, this section describes in more detail the 
code the user needs to provide in order for moving and copying to work correctly. We will use examples from the Zombies and Rumor demonstration models. See the {website}/examples/examples.html[Repast4Py Examples] page to download the source code for these models and for more information on getting started with the examples.

=== Agent ID
For moving and copying agents across processes to work each agent must have a unique id. 
This id has three components:

. An integer that uniquely identifies the agent on the rank on which it was created
. An integer that identifies its type
. The integer rank on which the agent was created

Combining the first component with the last allows us to uniquely identify an agent across the multi-process
simulation while the second allows us to create agents of the appropriate type when they are copied
between ranks. 

In order to ensure that all agents in Repast4Py have an agent id, all agents must inherit from the
{website}/apidoc/source/repast4py.core.html#repast4py.core.Agent[`repast4py.core.Agent`] class which requires these components in its constructor. For example, in the
Zombies demonstration model, the `Human` agents are subclasses of the `repast4py.core.Agent`.

[source,python,numbered]
----
class Human(repast4py.core.Agent): # <1>
    """The Human Agent

    Args:
        a_id: a integer that uniquely identifies this Human on its 
              starting rank
        rank: the starting MPI rank of this Human.
    """

    ID = 0

    def __init__(self, a_id: int, rank: int):
        super().__init__(id=a_id, type=Human.ID, rank=rank) #<2>
----
<1> Human inherits from `repast4py.core.Agent`
<2> Calling the `repast4py.core.Agent` constructor with the agent id
components.

The components as well as the full unique id are accessible as 
attributes of the `repast4py.core.Agent` class.

* id: the id component from the agent's unique id
* type: the type component from the agent's unique id
* rank: the rank component from the agent's unique id
* uid: the unique id tuple (id, type, rank)

[source,python,numbered]
----
>>> h = Human(12, 3)
>>> h.id
12
>>> h.rank
4
>>> h.type
0
>>> h.uid
(12, 0, 4)
----

IMPORTANT: All agents must subclass `repast4py.core.Agent`. See the {website}/apidoc/source/repast4py.core.html#repast4py.core.Agent[API documenation] for `repast4py.core.Agent` for more details of the `Agent` class.

=== Saving and Restoring Agents
Moving or copying an agent between processes consists of saving the agent state, moving / copying that state
to another process, and then restoring the agent state as an agent on the destination process. For this to work, each
agent is required to implement a `save` method that returns a tuple containing the full agent state. The first element of this 
full state tuple is the agent's unique id, itself a tuple (accessed via the `uid` attribute), and the second
is the dynamic state of that agent. For example, in the Zombie 
demonstration model the state of each Human is represented by two variables:

1. infected: a boolean that indicates whether or not the Human is infected
2. infected_duration: an integer tracking how long the agent has been infected

The `save` method creates a tuple consisting of these two variables and the unique id tuple.

[source,python,numbered]
----
def save(self) -> Tuple:
        """Saves the state of this Human as a tuple.

        Used to move this Human from one MPI rank to another.

        Returns:
            The saved state of this Human.
        """
        return (self.uid, self.infected, self.infected_duration)
----

NOTE: The agent state in the tuple returned from `save` can also consist of other tuples, lists 
and so on, in addition to primitive values, as long as the unique id tuple is the first element.

IMPORTANT: All agents must implement a `save` method.

You must also provide a `restore` function that takes the tuple produced by the `save` method and 
returns an agent either created from or updated with that state. The function is used during synchronization
to create the agents on the destination ranks. In the Zombies demonstration model, the `restore_agent`
function, when given agent state, returns Human and Zombie agents. It uses a caching scheme
to avoid re-instantiating agents that have previously been created on a rank, and updates the
state of those previously created agents. This can be a useful performance improvement at the
expense of using more memory.

[source,python,numbered]
----
agent_cache = {} #<1>

def restore_agent(agent_data: Tuple): #<2>
    """Creates an agent from the specified agent_data.

    This is used to re-create agents when they have moved from one MPI rank 
    to another. The tuple returned by the agent's save() method is moved 
    between ranks and create_agent is called for each tuple in order 
    to create the agent on that rank. Here we also use
    a cache to store any agents already created on this rank, 
    and only update their state rather than recreating them from scratch.

    Args:
        agent_data: the data from which to create the agent. This is the tuple
                    returned from the agent's save() method where the first
                    element is the agent id tuple, and any remaining 
                    arguments encapsulate agent state.
    """
    uid = agent_data[0]                                         #<3>
    # in uid element 0 is id, 1 is type, 2 is rank
    if uid[1] == Human.ID:                                      #<4>
        if uid in agent_cache:                                  #<5>
            h = agent_cache[uid] 
        else:
            h = Human(uid[0], uid[2])
            agent_cache[uid] = h

        # restore the agent state from the agent_data tuple
        h.infected = agent_data[1]                              #<6>
        h.infected_duration = agent_data[2]
        return h
    else:                                                       #<7>
        # note that the zombie has no internal state
        # so there's nothing to restore other than
        # the Zombie itself
        if uid in agent_cache:
            return agent_cache[uid]
        else:
            z = Zombie(uid[0], uid[2])
            agent_cache[uid] = z
            return z
----
<1> Cache for previously instantiated agents. Key is an agent's unique id (uid) tuple and value is the agent.
<2> `agent_data` is a tuple of the format produced by the `save` method. For Humans this is (uid, infected,
infected_duration). For Zombies, this is just (uid).
<3> The first element of the `agent_data` tuple is the uid tuple. The uid tuple is (id, type, starting rank).
<4> Checks if the agent is a Human or Zombie, using the type component of the uid.
<5> Checks if the agent is already cached, if so then get it (line 23), otherwise create a new `Human` agent
(line 25).
<6> Updates the cached / created Human with the passed in agent state.
<7> `agent_data` is for a Zombie so search cache and if necessary create a new one.

Lastly, in a distributed network, agents are not typically moved between processes
but rather the ghost agents remain on a process once the network is created. Repast4Py tracks 
these ghost agents and does not recreate the agents every synchronization step via a `restore`
method, instead a state update is sent to the appropriate ghost agents. In that case, an agent's `update` 
method is called to handle the state update. The Rumor demonstration model has an example of this.

[source,python,numbered]
----
class RumorAgent(core.Agent):

    ...

    def update(self, data: bool):    <1>
        """Updates the state of this agent when it is a ghost
        agent on some rank other than its local one.

        Args:
            data: the new agent state (received_rumor)
        """
        ...
        self.received_rumor = data
----
<1> Updates ghost agent state from saved agent state. Here the `data` argument
is only the dynamic state element of the tuple returned from the agent's `save` method, namely,
the `self.received_rumor` bool from `(self.uid, self.received_rumor)`.

=== Synchronization
As mentioned in the <<_distributed_simulation, Distributed Simulation>> section, each process in a
Repast4Py application runs in a separate memory space from all the other processes. Consequently,
we need to synchronize the model state across processes by moving agents, filling
projection buffers with ghosts, and updating ghosted states, as necessary. Synchronization
is performed by calling the
{website}/apidoc/source/repast4py.context.html#repast4py.context.SharedContext.synchronize[`SharedContext.synchronize`]method and passing it your restore function.
The `synchronization` method will use the agent `save` method(s) and your restore function
to synchronize the state of the simulation across its processes. 
