== Introduction
Repast for Python (Repast4Py) is a distributed agent-based simulation toolkit written in Python.
This introductory section will provide some conceptual background for a Repast-style simulation
as well as describing what it means for such a simulation to be (potentially) distributed
across multiple processes.

=== Contexts and Projections
Like the other members of the Repast ABM family, Repast4Py organizes a model in terms of *contexts* and *projections*. 
A context is a simple container based on set semantics. Any type of object can be put into a context, with the simple caveat that only one instance of any given object
can be contained by the context. From a modeling perspective, the context represents a population of agents. The agents in a context are the population of a model. 
However, the context does not inherently provide any relationship or structure for that population. Projections take the population as defined in a context 
and impose a structure on it. The structure defines and imposes relationships on the population using the semantics of the projection. Actual projections are 
such things as a network structure that allows agents to form links (network type relations) with each other, a grid where each agent is located in a 
matrix-type space, or a continuous space where an agent's location is expressible as a non-discrete coordinate. Projections have a many-to-one relationship with 
contexts. Each context can have an arbitrary number of projections associated with it. When writing a model, you will create a context, populate it with agents,
and attach projections to that context.

=== Scheduling Events
A Repast simulation moves forward by repeatedly determining the next event to execute and then executing that event.
Events in Repast simulations are driven by a discrete-event scheduler. These events themselves are scheduled to occur at a 
particular *tick*. Ticks do not necessarily represent clock-time but rather the priority of an associated event. 
Ticks determine the order in which events occur with respect to each other. For example, if event A is scheduled at tick 3 and 
event B at tick 6, event A will occur before event B.  Assuming nothing is scheduled at the intervening ticks, A will be 
immediately followed by B. There is no inherent notion of B occurring after a duration of 3 ticks.  Of course, ticks can and 
are often given some temporal significance through the model implementation. A traffic simulation, for example, may move the 
traffic forward the equivalent of 30 seconds for each tick. A floating point tick, together with the ability to order the 
priority of events scheduled for the same tick, provides for flexible scheduling. In addition, events can be scheduled dynamically 
such that the execution of an event may schedule further events at that same or at some future tick. When writing a model, you will
create a Schedule object, and schedule events, that is, Python methods or functions for execution at some particular time, or frequency.


