:fn-workflow-covid: footnote:[Ozik, J., Wozniak, J. M., Collier, N., Macal, C. M., & Binois, M. (2021). A population data-driven workflow for COVID-19 modeling and learning. The International Journal of High Performance Computing Applications, 35(5), 483–499. https://doi.org/10.1177/10943420211035164]
:fn-extreme-scale: footnote:[Ozik, J., Collier, N. T., Wozniak, J. M., Macal, C. M., & An, G. (2018). Extreme-Scale Dynamic Exploration of a Distributed Agent-Based Model With the EMEWS Framework. IEEE Transactions on Computational Social Systems, 5(3), 884–895. https://doi.org/10.1109/TCSS.2018.2859189]
:fn-r4py: footnote:[Collier, N. T., Ozik, J., & Tatara, E. R. (2020). Experiences in Developing a Distributed Agent-based Modeling Toolkit with Python. 2020 IEEE/ACM 9th Workshop on Python for High-Performance and Scientific Computing (PyHPC), 1–12. https://doi.org/10.1109/PyHPC51966.2020.00006]

== Getting Started
Repast for Python (Repast4Py) is the newest member of the https://repast.github.io[Repast Suite] of free and open source agent-based modeling and simulation software.
It builds on https://repast.github.io/repast_hpc.html[Repast HPC], and provides the ability to build large, distributed agent-based models (ABMs) that span multiple processing cores. 
Distributed ABMs enable the development of complex systems models that capture the scale and relevant details of many problems of societal importance.{wj}{fn-workflow-covid}{wj}{fn-extreme-scale}
Where Repast HPC is implemented in C++ and is more HPC expert focused, Repast4Py is a Python package and is designed to provide an easier on-ramp for researchers from diverse scientific communities to apply large-scale distributed ABM methods. Repast4Py is released under the BSD-3 open source license, and leverages https://numba.pydata.org[Numba], https://numpy.org[NumPy], and https://pytorch.org[PyTorch] packages, and the Python C API 
to create a scalable modeling system that can exploit the largest HPC resources and emerging computing architectures. See our paper on Repast4Py for additional information about the design and implementation.{wj}{fn-r4py}

=== Requirements

Repast4Py can run on Linux, macOS and Windows provided there is a working MPI implementation
installed and mpi4py is supported. Repast4Py is developed and tested on Linux. We recommend
that Windows users use the Windows Subsystem for Linux (WSL). Installation instructions for
WSL can be found https://docs.microsoft.com/en-us/windows/wsl/install[here].

Under Linux, MPI can be installed using your OS's package manager. For example, 
under Ubuntu 20.04 (and thus WSL), the mpich MPI implementation can be installed with:

[source,bash]
----
$ sudo apt install mpich
----

Installation instructions for MPI on macOS can be found {website}/macos_mpi_install.html[here].

A typical campus cluster, or HPC resource will have MPI and mpi4py installed.
Check the resource's documentation on available software for more details.

=== Installation

Repast4Py can be downloaded and installed from PyPI using pip. 
Since Repast4Py includes native MPI {cpp} code that needs to be compiled,
the C compiler `CC` environment variable must be set
to the `mpicxx` (or `mpic++`) compiler wrapper provided by your MPI installation.

----
env CC=mpicxx pip install repast4py
----

NOTE: If you see an error message about a missing `python.h` header file when
installing Repast4Py under Ubuntu (or other Linuxes), you will need to install
a python dev package using your OS's package manager. For example, assuming
Python 3.8, `sudo apt install python3.8-dev` will work for Ubuntu.

=== Documentation

* link:./user_guide.html[User's Guide] (This document)
* {website}/apidoc/index.html[API Docs]
* {website}/examples/examples.html[Example Models]

=== Contact and Support

* https://github.com/Repast/repast4py/issues[GitHub Issues]
* https://github.com/Repast/repast4py[GitHub Repository]


In addition to filing issues on GitHub, support is also available via
https://stackoverflow.com/questions/tagged/repast4py[Stack Overflow]. 
Please use the `repast4py` tag to ensure that we are notified of your question. 
Software announcements will be made on the 
http://lists.sourceforge.net/lists/listinfo/repast-interest[repast-interest] mailing list.

Jonathan Ozik is the Repast project lead. Please contact him through 
the https://www.anl.gov/staff-directory[Argonne Staff Directory] if you
have project-related questions.


== Why Repast4Py?
Modern high-performance computing (HPC) capabilities have allowed for large-scale computational modeling and experimentation. 
HPC clusters and supercomputers -- such as those hosted by universities, national laboratories, and cloud computing providers -- can have thousands or more processor cores available, allowing for high concurrency. 
Even individual CPUs now typically contain multiple cores, which are capable of running concurrently.
Distributed ABMs attempt to leverage this hardware by distributing an individual simulation over multiple processes running in parallel. 

However, in order to take advantage of these increasingly ubiquitous parallel computing resources, a computational model must first be refashioned to run on multiple processors. 
Adapting a computational model that was built for a single processor to run on multiple processors can be a nontrivial endeavor, both conceptually and practically.
Repast4Py aims to ease the transition to distributed ABMs by hiding much of the complexity.


=== Distributed computing a natural fit for agent-based modeling
A typical agent-based simulation consists of a population of agents each of which performs some behavior each timestep or at some frequency.
In practice, this is often implemented as a loop over the agent population in which each agent executes its behavior. 
The time it takes to complete the loop depends on the number of agents and the complexity of the behavior.
By distributing the agent population across multiple processes running in parallel, each process executes its own loop over only a subset of the population, allowing for larger agent populations and more complex behavior.

=== Repast4Py and the broader Repast family
While Repas4Py is meant to make the development of distributed ABMs easier, we encourage users new to the Repast Suite to look through the different versions of https://repast.github.io/docs.html[Repast] to determine which toolkit is most appropriate for their needs. Of note, we recommend users new to agent-based modeling to first check out https://repast.github.io/repast_simphony.html[Repast Simphony] to develop a better understanding of the concepts behind agent-based modeling and learn how to quickly build such models.

The following sections will provide some conceptual background for a Repast-style simulation, describe how such a simulation is distributed across multiple processes with Repast4Py, and end with providing a few basic tutorials.





