== Why Repast4py?
Repast for Python (Repast4Py) is the newest member of the https://repast.github.io[Repast Suite] of free and open source agent-based modeling and simulation software.
It builds on https://repast.github.io/repast_hpc.html[Repast HPC], and provides the ability to build large, distributed agent-based models (ABMs) that span multiple processing cores. 
Distributed ABMs enable the development of complex systems models that capture the scale and relevant details of many problems of societal importance #QUESTION: CAN WE INCLUDE REFERENCES HERE?#
Where Repast HPC is implemented in C++ and is more HPC expert focused, Repast4Py uses Python and is designed to provide an easier on-ramp for researchers from diverse scientific communities to apply large-scale distributed ABM methods. 


=== Meeting the era of "Big computing"
Modern high-performance computing (HPC) capabilities have allowed for large-scale computational modeling and experimentation. 
HPC clusters and supercomputers -- such as those hosted by universities, national laboratories, and cloud computing providers -- can have thousands or more processor cores available, allowing for high concurrency. 
Even individual CPUs now typically contain multiple cores, which are capable of running concurrently.
Distributed ABMs attempt to leverage this hardware by distributing an individual simulation over multiple processes running in parallel. 

However, in order to take advantage of these increasingly ubiquitous parallel computing resources, a computational model must first be refashioned to run on multiple processors. 
Adapting a computational model that was built for a single processor to run on multiple processors is a nontrivial endeavor, both conceptually and practically.
// TODO - Do I want to expand on the difficulties of parallelizing code? 
//  Difficulties such as: 
//  - include deciding on the components of a model that can run concurrently, 
//  - anticipating where bottlenecks and/or failures might occur, and 
//  - coordinating the message passing between such components.
Repast4py aims to ease the transition to distributed ABMs by hiding much of the complexity.


=== Distributed computing a natural fit for agent-based modeling
A typical agent-based simulation consists of a population of agents each of which performs some behavior each timestep or at some frequency.
In practice, this is often implemented as a loop over the agent population in which each agent executes its behavior. 
The time it takes to complete the loop depends on the number of agents and the complexity of the behavior.
By distributing the agent population across multiple processes running in parallel, each process executes its own loop over only a subset of the population, allowing for larger agent populations and more complex behavior, ideally without increasing the runtime too much. 

=== Repast4py and the broader Repast family
While Repas4Py is meant to make the development of distributed ABMs easier, we encourage  users new to the Repast Suite to look through the different versions of https://repast.github.io/docs.html[Repast] to determine which toolkit is most appropriate for their needs.
Of note, we recommend users new to agent-based modeling to first check out https://repast.github.io/repast_simphony.html[Repast Simphony] to develop a better understanding of the concepts behind agent-based modeling and learn how to quickly build such models.

The following sections will provide some conceptual background for a Repast-style simulation, describe how such a simulation is distributed across multiple processes with Repast4py, and end with providing a few basic tutorials.





