== Why Repast4py?
// TODO add in a more general intro here that succinctly mentions why Repast4py is so important
// TODO clean all of the sections up

=== Repast4py and the Repast family
Repast for Python (Repast4Py) is a distributed agent-based simulation toolkit written in Python, and is a part of the broader https://repast.github.io[Repast Suite] of free and open source agent-based modeling and simulation software.
// TODO add more here

While modern computing capabilities has allowed large-scale XX to occur, one of the most difficulties is converting computational models to run in multiple processors, rather than an individual one. 
// TODO clean this up 

=== Meeting the era of "Big computing"
Modern CPUs typically contain multiple cores, each of which is capable of running concurrently.
Repast4Py attempts to leverage this hardware by distributing a simulation over multiple processes
running in parallel on these cores.
A typical agent-based simulation consists of a population of agents each of which performs some behavior each timestep or at some frequency.
In practice, this is often implemented as a loop over the agent population in which each agent executes its behavior. 
The time it takes to complete the loop depends on the number of agents and the complexity of the behavior.

=== Distributed computing a natural fit for agent-based modeling
By distributing the agent population across multiple processes running in parallel, each process executes its own loop over only a subset of the population, allowing for larger agent populations and more complex behavior without increasing the runtime. 
Repast4Py is also a natural fit for implementing agent-based simulations on high performance computers and clusters, such as those hosted by universities, national laboratories, and cloud computing providers. 
Such machines can have thousands or 10s of thousands of processor cores available, allowing for very large and complex simulations.

The following sections will provide some conceptual background for a Repast-style simulation as well as describing how such a simulation is distributed across multiple processes. We end with providing a basic tutorial.





