== Components of a Repast agent-based model
Like the other members of the Repast ABM family, Repast4Py organizes a model in terms of *_contexts_*, *_agents_*, and *_projections_*. Additionally, Repast4py uses *_discrete events_* implemented as schedules to drive the model through time. To log simulation data, a logger object is XX. 
//TODO 

=== Agents
// TODO
Objects with attributes and behavior. These attributes are implemented as XX, and the behavior is implemented using methods. 
Agents populate a model via its context.

=== Contexts 
A context is a simple container based on set semantics. 
Any type of object can be put into a context, with the simple caveat that only one instance of any given object can be contained by the context. 
From an agent-based modeling perspective, the context represents a population of agents. 
The agents in a context are the population of a model. 
However, the context does not inherently provide any relationship or structure for that population. 

=== Projections
Projections take the population as defined in a context and impose a structure on it. 
The structure defines and imposes relationships on the population using the semantics of the projection. 
Actual projections are such things as a network structure that allows agents to form links (network type relations) with each other, a grid where each agent is located in a matrix-type space, or a continuous space where an agent's location is expressible as a non-discrete coordinate. 
Projections have a many-to-one relationship with contexts. 
Each context can have an arbitrary number of projections associated with it. 
When writing a model, you will create a context, populate it with agents, and attach projections to that context.

=== Discrete Event Scheduling
A Repast simulation moves forward by repeatedly determining the next event to execute and then executing that event.
Events in Repast simulations are driven by a discrete-event scheduler. 
These events themselves are scheduled to occur at a particular *_tick_*. 
Ticks do not necessarily represent clock-time, but rather the priority of an associated event. 
Ticks determine the order in which events occur with respect to each other. 
For example, if Event A is scheduled at tick 3 and Event B at tick 6, then Event A will occur before Event B.  
Assuming nothing is scheduled at the intervening ticks, Event A will be immediately followed by Event B. 
There is no inherent notion of Event B occurring after a duration of 3 ticks.  
Of course, ticks can and are often given some temporal significance through the model implementation. A traffic simulation, for example, may move the traffic forward the equivalent of 30 seconds for each tick. 
Events can also be scheduled dynamically such that the execution of an event may schedule further events at that same or at some future tick. 
When writing a model, you will create a *_Schedule object_*, and schedule events as Python methods or functions for execution at some particular tick, or tick frequency.

=== Logging
//TODO 