:icons: font
:website: http://repast.github.io
:xrefstyle: full
:imagesdir: ./images
:source-highlighter: pygments

== Installing Repast4Py on Windows without MPI

On Windows, Repast4Py can also be installed from a pre-built Python wheel in a *no-mpi* mode that requires neither a native MPI installation, mpi4py, nor a C/C++ compiler. In this mode, other, non-MPI-based parallelism, such as Python's built-in multiprocessing or thread-based parallelism, can be used to develop models. This mode also makes native windows installation
easier, as an mpi distribution may be difficult to install.

IMPORTANT: Do not install the no-mpi version and the mpi version of Repast4Py in the same Python environment.

// NOTE: We recommend that Windows users use the Windows Subsystem for Linux (WSL) in order
// take advantage of MPI and mpi4py to build distributed models. 
// Installation instructions for
// WSL can be found https://docs.microsoft.com/en-us/windows/wsl/install[here]. 

The preferred install is into a Python virtual environment. To
create the environment, in a `powershell` or `cmd` terminal do:

.Powershell
[source,powershell]
----
python -m venv path\to\repast4py_venv
path\to\repast4py_venv\Scripts\Activate.ps1
----

.CMD
[source,cmd]
----
python -m venv path\to\repast4py_venv
path\to\repast4py_venv\activate.bat
----

The environment only needs to be created once with `python -m venv ...`,
but does need to be activated each time in order to be used. For
more information see the `venv` Python documentation
https://docs.python.org/3/library/venv.html[here]

=== Installation steps

1. Download the wheel that matches your Python version

* 3.10: https://github.com/Repast/repast4py/releases/download/v1.3.0/repast4py-1.3.0-cp310-cp310-win_amd64.whl[repast4py-1.3.0-cp310-cp310-win_amd64.whl]
* 3.11: https://github.com/Repast/repast4py/releases/download/v1.3.0/repast4py-1.3.0-cp311-cp311-win_amd64.whl[repast4py-1.3.0-cp311-cp311-win_amd64.whl]
* 3.12: https://github.com/Repast/repast4py/releases/download/v1.3.0/repast4py-1.3.0-cp312-cp312-win_amd64.whl[repast4py-1.3.0-cp312-cp312-win_amd64.whl]
* 3.13: https://github.com/Repast/repast4py/releases/download/v1.3.0/repast4py-1.3.0-cp313-cp313-win_amd64.whl[repast4py-1.3.0-cp313-cp313-win_amd64.whl]
* 3.14: https://github.com/Repast/repast4py/releases/download/v1.3.0/repast4py-1.3.0-cp314-cp314-win_amd64.whl[repast4py-1.3.0-cp314-cp314-win_amd64.whl]

2. Install the wheel in your Python environment
+
Be sure your environment is activated, and from a `powershell` or `cmd` terminal
+
.Powershell
[source,powershell]
----
path\to\repast4py_venv\Scripts\Activate.ps1
$env:R4PY_NO_MPI=1
pip install <wheel>
----
+
.CMD
[source,cmd]
----
path\to\repast4py_venv\activate.bat
set R4PY_NO_MPI=1
pip install <wheel>
----
+
Replace `<wheel>` with the path to the downloaded wheel. At this point, Repast4Py should be
ready to use in the activated environment.
